backend:
  name: git-gateway
  branch: master

media_folder: "/assets/data"
public_folder: "/assets/data"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    media_folder: ""
    public_folder: ""
    create: true
    slug: "article_{{title|slugify}}_{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Collaborators", name: "collaborators", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["article"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Image caption", name: "imageAlt", widget: "string", required: false}